import {StyleSheet} from 'react-native';
let _defz = require('../../com/def');

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    backgroundColor: '#000',
  },
  scrollViewH2: {
    position: 'absolute',
    bottom: 70,
    left: 0,
    zIndex: 99999999,
  },
  searchTypeText: {
    fontFamily: 'FuturaPT-Medium',
    fontSize: 20,
    color: '#707070',
    textAlign: 'center',
    width: '100%',
  },
  searchTypeTextActive: {
    fontFamily: 'FuturaPT-Medium',
    fontSize: 20,
    color: '#3D80F2',
    textAlign: 'center',
    width: '100%',
  },
  touch_style_close: {
    backgroundColor: '#F0F0F0',
    marginLeft: _defz.width / 15,
    borderRadius: 10,
    width: _defz.width / 2.3,
    marginTop: 'auto',
  },
  touch_style_open: {
    backgroundColor: 'white',
    marginLeft: _defz.width / 15,
    borderRadius: 10,
    width: _defz.width / 2.3,
    marginTop: 'auto',
  },
  text_borrow: {
    fontSize: 12,
    color: '#707070',
    marginLeft: '9%',
    fontFamily: 'FuturaPT-Book',
  },
  sliderImages: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    maxWidth: '100%',
    height: _defz.height / 6,
  },
  text_address: {
    marginLeft: '5%',
    marginTop: 2,
    fontSize: 10,
    fontFamily: 'FuturaPT-Medium',
  },
  text_title_shop: {
    marginLeft: 5,
    marginTop: 5,
    fontSize: 18,
    fontFamily: 'FuturaPT-Medium',
  },
  text_title_shop_number: {
    marginLeft: 5,
    marginTop: 8,
    fontSize: 14,
    fontFamily: 'FuturaPT-Medium',
  },
  view_line: {
    width: '70%',
    alignSelf: 'center',
    height: 5,
    borderRadius: 15,
    marginVertical: 5,
    backgroundColor: 'black',
  },
  view_line_b: {
    width: '70%',
    alignSelf: 'center',
    height: 4,
    borderRadius: 15,
    marginTop: 5,
    backgroundColor: 'black',
    position: 'absolute',
    flex: 1,
    zIndex: 999,
  },

  map: {
    marginTop: 80,
    width: _defz.width,
    position: 'relative',
    flex: 1,
    overflow: 'hidden',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  transparentHeader: {
    zIndex: 999999,
    alignSelf: 'center',
    width: '100%',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    position: 'absolute',
    top: 52,
  },
  view_line_b: {
    width: '50%',
    alignSelf: 'center',
    height: 2,
    borderRadius: 15,
    marginTop: '5%',
    backgroundColor: 'black',
    position: 'absolute',
    zIndex: 999,
  },
  footer: {
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
    height: 66,
    borderTopColor: '#C3BCBC',
    backgroundColor: '#fff',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  searchBox: {
    width: '70%',
    position: 'relative',
    left: 25,
    bottom: 3,
  },
  footerSearchInput: {
    borderColor: '#3D80F2',
    borderWidth: 2,
    width: '100%',
    borderRadius: 30,
    textAlign: 'center',
    color: '#3D80F2',
  },
  searchImage: {
    position: 'absolute',
    left: 20,
    bottom: 15,
  },
  homeButton: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: _defz.height / 40,
  },
  headerBackButton: {
    width: '40%',
    height: 10,
    backgroundColor: '#000',
    borderRadius: 50,
    marginTop: 5,
    alignSelf: 'center',
  },
  mapHeaderBackButton: {
    width: '40%',
    height: 10,
    backgroundColor: '#000',
    borderRadius: 50,
    marginTop: '8%',
    alignSelf: 'center',
  },
  content: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    position: 'relative',
    top: 80,
    
    backgroundColor: '#F0F0F0',
  },
  contentTransparent: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    backgroundColor: '#000',
  },
  searchBoxTop: {
    width: '100%',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchInput: {
    width: '90%',
    alignSelf: 'center',
    borderColor: '#C3BCBC',
    borderWidth: 1,
    padding: '2%',
    marginTop: '2%',
    borderRadius: 40,
    elevation: 2,
    textAlign: 'center',
  },
  productCards: {
    width: '100%',
    position: 'absolute',
    top: 145,
  },
  scrollViewV: {
    width: '100%',
    height: _defz.height / 1.3,
  },
  products: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    paddingBottom: 30,
    paddingRight: '2%',
    paddingLeft: '2%',
  },
  searchTypeButtons: {
    width: 208,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#F0F0F0',
    elevation: 3,
    paddingHorizontal: 10,
    borderRadius: 50,
    height: 44,
    marginTop: 5,
    zIndex: 0
  },
  searchTypeButton: {
    alignSelf: 'center',
    width: 100,
    textAlign: 'center',
    height: 38,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  searchTypeButtonActive: {
    borderWidth: 1.5,
    borderColor: '#3D80F2',
    borderRadius: 50,
    paddingHorizontal: '3%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#fff',
    height: 38,
    width: 100,
  },
  header: {
    backgroundColor: 'transparent',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 30,
    marginTop: -20,
  },
  search_box: {
    borderRadius: 50, 
    elevation: 6, 
    position: 'relative',
  },
  search_input: {
    color: 'gray',
    fontFamily: 'FuturaPT-BookObl',
    fontSize: 18,
    borderRadius: 15,
  },
  homeButtonWithBadge: {
    position: 'relative',
  },
  badgeCircle: {
    position: 'absolute',
    right: -5,
    top: 10,
    backgroundColor: '#E03174',
    borderRadius: 400,
    width: 20,
    height: 20,
    zIndex: 10,
  },
});
