import {StyleSheet} from 'react-native';
let _defz = require('../../com/def');

export const styles = StyleSheet.create({
  sotreFront: {
    padding: '2%',
    paddingTop: 30,
    flex: 1,
    width: '100%',
    backgroundColor: '#FAFAFA',
  },
  header: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '3%',
  },
  headerRigth: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  msgButton: {
    marginTop: '2%',
  },
  backButton: {
    marginBottom: _defz.height / 80,
  },
  types: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  scrollViewH: {
    width: '100%',
    
  },
  productCards: {
    width: '100%',
    marginTop: '3%',
  },
  scrollViewV: {
    width: '100%',
    height: _defz.height / 1.2,
  },
  products: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    width: '95%',
    alignSelf: 'center',
  },
  footer: {
    width: _defz.width,
    paddingLeft: 20,
    paddingRight: 20,
    height: 66,
    borderTopColor: '#C3BCBC',
    backgroundColor: '#fff',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  searchBoxButton: {
    alignSelf: 'center',
  },
  searchInput: {
    borderColor: '#707070',
    borderWidth: 1,
    width: '100%',
    borderRadius: 30,
    textAlign: 'center',
  },
  searchImage: {
    position: 'absolute',
    left: 20,
    bottom: 15,
  },
  homeButton: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: _defz.height / 40,
  },
  cart: {
    borderRadius: 40,
    borderColor: '#C3BCBC',
    borderWidth: 1,
    paddingLeft: '5%',
    paddingRight: '5%',
    marginLeft: 5,
    marginRight: 5,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 35,
    width: _defz.width / 3.5,
    elevation: 3,
    backgroundColor: '#fff',
  },
  active: {
    borderColor: '#3D80F2',
    borderRadius: 40,
    borderWidth: 1,
    paddingLeft: '5%',
    paddingRight: '5%',
    marginLeft: 5,
    marginRight: 5,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 35,
    width: _defz.width / 3.5,
    elevation: 3,
    backgroundColor: '#fff',
  },
  activeText: {
    color: '#3D80F2',
    fontSize: 14,
    fontFamily: 'FuturaPT-Medium',
  },
  text: {
    fontSize: 14,
    fontFamily: 'FuturaPT-Medium',
    color: '#707070',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    position: 'relative',
  },
  modalView: {
    width: '90%',
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  pickupHeading: {
    marginTop: 10,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',

  },
  styles_names:{
    fontFamily: 'FuturaPTDemi',
    fontSize: 22,
    color: "#707070"
  },
  styles_names2:{
    fontFamily: 'FuturaPTDemi',
    fontSize: 19,
    color: "#707070",

  },
  pickupInfo: {
    marginTop: 10,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  workTimes: {
    marginTop: 10,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  workTime: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: _defz.width / 2.5,
  },
  workTimeText: {
    color: '#707070',
  },
  modalCloseButton: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  modalCloseIcon: {
    color: '#707070',
    fontSize: 30,
  },
  optionsContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: _defz.height / 35,
  },
  modalOptionsHeading: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOptions: {
    width: _defz.width / 1.3,
    height: _defz.height / 15,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: '1%',
  },
  pickupOption: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  checkButton: {
    fontSize: 20,
  },
  optionText: {
    color: '#000',
  },
  vendorName: {
    fontFamily: 'FuturaPT-Demi',
    fontSize: 22,
  },
  homeButtonWithBadge: {
    position: 'relative',
  },
  badgeCircle: {
    position: 'absolute',
    right: -5,
    top: 10,
    backgroundColor: '#E03174',
    borderRadius: 400,
    width: 20,
    height: 20,
    zIndex: 10,
  },
});
