import {StyleSheet} from 'react-native';
let _defz = require('../../com/def');

export const styles = StyleSheet.create({
  header: {
    backgroundColor: 'black',
  },
  headerXbutton: {
    alignSelf: 'flex-end',
    marginTop: 5,
  },
  noAddress: {
    width: '100%',
    height: '100%',
    backgroundColor: '#FAFAFA',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  headerXIcon: {
    alignSelf: 'center',
    color: 'silver',
    fontSize: 35,
    margin: 5,
  },
  container: {
    backgroundColor: '#FAFAFA',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  addressCard: {
    borderColor: '#707070',
    borderWidth: 1,
    elevation: 6,
    backgroundColor: '#fff',
    width: '85%',
    borderRadius: 10,
    paddingLeft: '10%',
    paddingRight: '10%',
    paddingTop: '5%',
    paddingBottom: '5%',
    position: 'relative',
    marginTop: 30,
  },
  activeCard: {
    borderColor: '#3D80F2',
    borderWidth: 2,
    elevation: 6,
    backgroundColor: '#fff',
    width: '85%',
    borderRadius: 10,
    paddingLeft: '10%',
    paddingRight: '10%',
    paddingTop: '5%',
    paddingBottom: '5%',
    position: 'relative',
    marginTop: 10,
  },
  closeEditButton: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  closeEditButtonIcon: {
    color: '#707070',
  },
  scrollView: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    marginBottom: _defz.height / 3.33,
  },
  addressCardFooter: {
    backgroundColor: '#F0F0F0',
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: '2%',
    borderRadius: 10,
    elevation: 6,
    height: 50,
    paddingTop: 10,
    marginTop: _defz.height / 30,
  },
  addressCardFooterButton: {
    borderRadius: 50,
    height: _defz.height / 35,
    backgroundColor: '#fff',
    position: 'relative',
    elevation: 4,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 100,
  },
  primaryButtonActive: {
    borderRadius: 50,
    height: _defz.height / 35,
    backgroundColor: '#fff',
    position: 'relative',
    elevation: 4,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 100,
  },
  addressCardFooterButtonEdit: {
    borderRadius: 50,
    height: _defz.height / 30,
    backgroundColor: '#C3BCBC',
  },
  addressCardFooterTextEdit: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'FuturaPT-Book',
    paddingVertical: 2,
    paddingHorizontal: 20,
  },
  primaryButton: {
    borderColor: '#3D80F2',
    backgroundColor: '#fff',
  },
  primaryText: {
    color: '#3D80F2',
    fontSize: 14,
    fontFamily: 'FuturaPT-Medium',
  },
  primaryText1: {
    color: '#3D80F2',
    fontSize: 14,
    fontFamily: 'FuturaPT-Medium',
    marginLeft: 28,
  },
  addressCardFooterText: {
    color: '#C3BCBC',
    fontFamily: 'FuturaPT-Medium',
    fontSize: 14,
  },
  activeEditButton: {
    borderColor: '#fff',
    backgroundColor: '#3D80F2',
    borderRadius: 50,
    borderWidth: 1,
    height: _defz.height / 30,
  },
  activePrimaryButton: {
    borderColor: '#3D80F2',
    backgroundColor: '#fff',
    borderRadius: 50,
    borderWidth: 2,
    height: _defz.height / 30,
    minWidth: 100,
  },
  activeEditText: {
    color: '#fff',
    fontFamily: 'FuturaPT-Book',
    fontSize: 14,
    paddingVertical: 2,
    paddingHorizontal: 20,
  },
  textInput: {
    borderBottomColor: '#707070',
    borderBottomWidth: 1,
    marginVertical: 8,
    color: '#C3BCBC',
    fontFamily: 'FuturaPT-Book',
    fontSize: 18,
  },
  addresText: {
    fontSize: 18,
    fontFamily: 'FuturaPT-Medium',
    color: '#707070',
  },
  notPrimaryConainer: {
    position: 'relative',
  },
  footerButtonXIcon: {
    fontSize: 25,
    color: 'silver',
    position: 'absolute',
    right: -40,
    top: -4,
  },
  footerButtonXIconPrimary: {
    color: '#3D80F2',
    position: 'absolute',
    right: -12,
  },
  notPrimaryText: {
    color: 'silver',
    fontSize: 14,
    fontFamily: 'FuturaPT-Medium',
  },
  arrowBack: {
    flex: 1,
  },
  headerText2: {
    color: '#707070',
    fontSize: 35,
    alignSelf: 'center',
    textAlign: 'center',
    fontFamily: 'FuturaPT-Medium',
    flex: 3,
    marginLeft: '-18%',
    padding: '2%',
  },
  headerContainer: {
    minHeight: _defz.height / 15,
    marginTop: _defz.height / 50,
    backgroundColor: '#FAFAFA',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-between',
    padding: '2%',
  },
  userName: {
    fontSize: 18,
    fontFamily: 'FuturaPT-Medium',
    color: '#707070',
  },
});
